name: GitHub 3D Contribution Graph

on:
  schedule:
    - cron: "0 1 * * *" # Once a day at 04:00 Israel Time (01:00 UTC)
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "*.svg"
      - "profile-3d-contrib/**"
      - "dist/**"
      - "README.md"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-3d-contrib-svg
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: OSK0020
      - name: Commit & Push 3D Contrib SVGs
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add profile-3d-contrib
          if ! git diff --cached --quiet; then
            git commit -m "Auto-update 3D Contribution Graph"
            for i in {1..5}; do
              git pull --rebase origin main && git push origin main && break || sleep $((i * 3))
            done
          else
            echo "No changes to commit"
          fi
